# load pause image before kubelet starts
[Service]
Environment=CONTAINERD_SNAPSHOTTER=overlayfs
EnvironmentFile=-/etc/eks/containerd_snapshotter
ExecStartPre=/usr/bin/ctr --namespace=k8s.io image import --snapshotter "$CONTAINERD_SNAPSHOTTER" --discard-unpacked-layers=false --local /etc/eks/pause.tar
ExecStartPre=/usr/bin/ctr --namespace=k8s.io image label localhost/kubernetes/pause:latest io.cri-containerd.pinned=pinned
